apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  resourceGroup: {{resource_group.name}}
  computerName: {{match_resource.resource.get("computerName")}}
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/redis-logo.svg
  owners:
  - {{workspace.owner_email}}
  statement: Redis endpoints should be responsive and healthy state. 
