apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
    dummy: foobar-update3
spec: 
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/k8s-redis-healthcheck/runbook.robot
  configProvided:
    - name: REDIS_HEALTHCHECK_KEY
      value: runwhen_task_rw_healthcheck
